cloud_provider: aws
reserved_ip_enabled: true
ssl_cert_method: acm
monitoring_agent: cloudwatch

# AWS Configuration
aws_region: "{{ lookup('env', 'AWS_REGION') | default('us-east-1') }}"
configure_security_group: true

# GitHub Actions
setup_github_actions: true
