repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^src/config/static/vendor/.*$
      - id: check-yaml
        exclude: ^docker/mkdocs/mkdocs\.yml$
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        files: ^src/.*\.py$
      - id: ruff-format
        args: [--check]
        files: ^src/.*\.py$

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd src/frontend && npx eslint "${@#src/frontend/}"' --
        language: system
        files: ^src/frontend/src/.*\.(js|jsx)$
        pass_filenames: true

      - id: prettier
        name: prettier
        entry: bash -c 'cd src/frontend && npx prettier --check "${@#src/frontend/}"' --
        language: system
        files: ^src/frontend/src/.*\.(js|jsx|ts|tsx|json|css)$
        pass_filenames: true
