repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff
        files: ^src/.*\.py$
      - id: ruff-format
        args: [--check]
        files: ^src/.*\.py$

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx --prefix src/frontend eslint
        language: system
        files: ^src/frontend/src/.*\.(js|jsx)$
        pass_filenames: true

      - id: prettier
        name: prettier
        entry: npx --prefix src/frontend prettier --check
        language: system
        files: ^src/frontend/src/.*\.(js|jsx|ts|tsx|json|css)$
        pass_filenames: true
