name: CI Tests

on:
  workflow_call: {}
  push:
    branches: [develop, staging, main]
  pull_request:
    branches: [develop, staging, main]

jobs:
  test-backend:
    name: Test Django Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Create test .env file
      run: cp dev.env .env

    - name: Build Docker images
      run: docker compose -f compose.dev.yml build

    - name: Run Django tests
      run: docker compose -f compose.dev.yml run --rm django poetry run pytest

    - name: Cleanup
      if: always()
      run: docker compose -f compose.dev.yml down -v

  test-frontend:
    name: Test React Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./src/frontend
      run: npm ci

    - name: Run frontend tests
      working-directory: ./src/frontend
      run: npm test --if-present

    - name: Build frontend
      working-directory: ./src/frontend
      run: npm run build
